server:
  port: 8080
canal:
  client:
    instances:
      example:
        host: 47.103.18.23
        port: 11111
        batchSize: 1000
        userName: root
        password: YYQKitty123
spring:
  main:
    allow-bean-definition-overriding: true